services:
  novabot:
    build: .
    container_name: novabot
    restart: unless-stopped
    env_file:
        - .env
    environment:
      PORT: "7860"
    ports:
        - "7860:7860"
    volumes:
        - ./data:/app/data:ro